class_name Maze
extends TileMapLayer
## Maze based on [TileMapLayer].
##
## If generated by [method MazeGenerator.generate],
##  will have a border (width=1) of wall around.


const black_and_white_atlas__source_id := 0

const white_tile__atlas_coord := Vector2i(0, 0)

const black_tile__atlas_coord := Vector2i(1, 0)

const length_of_tile := 16

var width: int

var height: int

## Vector2i(x_coord, y_coord), unit is [code]tile[/code], starts with 0.
var exit_gate__coord := Vector2i.ZERO

## Vector2i(x_coord, y_coord), unit is [code]tile[/code], starts with 0.
##  [code]Vector2i(-1, -1)[/code] means does not exist.
var relic__coord: Vector2i = Vector2i(-1, -1)

## Test if this maze has relic.
var has_relic: bool:
    get():
        return self.relic__coord != Vector2i(-1, -1)

## Vector2i(x_coord, y_coord), unit is [code]tile[/code], starts with 0.
##  [code]Vector2i(-1, -1)[/code] means does not exist.
var quarter__coord: Vector2i = Vector2i(-1, -1)

## Test if this maze has quarter.
var has_quarter: bool:
    get():
        return self.quarter__coord != Vector2i(-1, -1)


## Check whether the cell at given maze coord, is not a path.
func isNotPathAt(x: int, y: int):
    return x > self.width - 1 or y > self.height - 1 \
        or self.get_cell_atlas_coords(Vector2i(x, y)) != Maze.white_tile__atlas_coord

## Update [TileMapLayer]'s internal,
##  then update [member width] and [member height].
func updateInternals():
    self.update_internals()
    var used_rect = self.get_used_rect()
    self.width = used_rect.size.x
    self.height = used_rect.size.y

func _init() -> void:
    self.tile_set = preload("res://assets/tilesets/maze/monocolour_tileset.tres")
